export const cartActions = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  GET_ALL_CART_ITEMS: "GET_ALL_CART_ITEMS",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  UPDATE_CART_ITEM_QTY: "UPDATE_CART_ITEM_QTY",
};
