export const wishlistActions = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  GET_ALL_WISHLIST: "GET_ALL_WISHLIST",
  ADD_PRODUCT_TO_WISHLIST: "ADD_PRODUCT_TO_WISHLIST",
  REMOVE_PRODUCT_FROM_WISHLIST: "REMOVE_PRODUCT_FROM_WISHLIST",
};
